### ISSUE TITLE
Roadmap to Hackathon Starter 2.0

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#112]
- [x] Use releases, e.g. v2.0.0, 2.0.1, instead of `git clone` master branch.
- [x] Add CHANGELOG section to Readme.
- [x] API examples listed as a grid of small columns (`col-xs-2` or `col-xs-3`) per row.
- [x] CSRF: Rename `token` local variable to `_csrf`.
- [x] Move demo site to Nodejitsu.
- [x] ~~Landing page similar to [Keystone.js](http://keystonejs.com/) or the [official Github Pages](http://pages.github.com/) site.~~
- [x] Display all API logos that are listed in API Examples
- [x] ~~Instagram API example.~~ (TBD)
- [x] Stripe API example.
- [x] ~~Simplify and refactor Paypal example.~~ (Replaced by Stripe)
- [x] Wiki page for sites that are using Hackathon Starter.
- [x] Move to Express 4.0
- [x] Generator (Auth-only for now, needs more testing on `generator` branch)
